alias reload!='. ~/.zshrc'
alias h='history'
alias l="ls -lAh"
alias ll="ls -l"
alias la='ls -A'
alias lla='ls -lA'
alias v='mvim --remote-silent'
alias git='hub'
alias nginx-restart="sudo launchctl unload -w  /System/Library/LaunchDaemons/org.nginx.plist && sudo launchctl load -w  /System/Library/LaunchDaemons/org.nginx.plist"
alias luad='~/src/lua/LuaDist-Batteries/bin/lua'
